config/routes.rb
Rails.application.routes.draw do
  devise_for :users  
  # devise_scope :user do
  #   delete "/users/sign_out", to: "devise/sessions#destroy"
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "albums#index"
  get '/my_albums' ,to: 'albums#my_albums'
  get 'tags/:tag', to: 'albums#index', as: :tag



  resources :albums do
    member do
      delete :remove_image
    end
  end
 # delete "/albums/:id/images/:id" ,to: "images#remove_image"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, presence: true
    has_one_attached :cover_image
    has_many_attached :images

    def self.ransackable_attributes(auth_object = nil)
        ["body", "created_at", "id", "published", "title", "updated_at"]
    end

    has_many :taggings, dependent: :destroy
    has_many :tags,through: :taggings

    def self.tagged_with(name)
      Tag.find_by!(name: name).albums
    end
    
    def self.tag_counts
      Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
    end
  
    def tag_list
      tags.map(&:name).join(', ')
    end
  
    def tag_list=(names)
      self.tags = names.split(',').map do |n|
        Tag.where(name: n.strip).first_or_create!
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings 
    has_many :albums ,through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!,except: [:index] 
 
  def index
    @q = Album.ransack(params[:q])
    @albums = @q.result(distinct: true).where(published: true)
    params[:tag] ? @albums= Album.tagged_with(params[:tag]) : @Albums = Album.all
    # @albums = Album.where(published: true)
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album= Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to @album
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to root_path, status: :see_other
  end

  def remove_image
   
    album = Album.find(params[:id])
    image = album.images.find(params[:image_id])
    image.purge
    redirect_back fallback_location: root_path,notice:"success"
  end

  def my_albums
    
    @albums = Album.where(published: false)
  end

  private
  def album_params
    params.require(:album).permit(:title, :body , :cover_image, :published , :tag_list, :tag, { tag_ids: [] }, :tag_ids, images: [])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<div class=" container-fluid d-flex justify-content-center ">
<%= form_with(model: @album, local:true)do |form| %>
<div class=" container form_border p-2">
  <div class="fs-5" >
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @album.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div class="fs-5">
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @album.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div class="field fs-5">
    <%= form.label :published%>
    <%= form.check_box :published%> 
      <br />
  </div><br>

  <div class="fs-5">
    <%= form.label :cover_image  %><br>
    <%= form.file_field :cover_image  %>
  </div><br>

  <div class="fs-5">
    <%= form.label :images %><br>
    <%= form.file_field :images ,multiple: true, direct_upload: true %>
  </div><br>

  <div class= "form-group">
    <%= form.label :tag_ids, 'Tags' %>
    <%= form.select :tag_ids, options_from_collection_for_select(Tag.order(:name), :id, :name, form.object.tag_ids), { include_blank: true }, { multiple: true } %>
  </div><br>

  <div>
     <%= form.submit class:"btn btn-danger" %>
  </div>
<% end %>
</div>
</div>

app/views/albums/edit.html.erb
<div class="container-fluid h-100 bgimg ">
<h1 class="text-danger text-center ">Edit Album</h1><br>
<%= render "form", album: @album %>
</div>

app/views/albums/index.html.erb
<h1 class="text-center p-3 text-danger">Albums</h1>
<div class="row container-fluid">

<%= search_form_for @q do |form| %>
  <div class="d-flex justify-content-end mb-3">
  <%= form.search_field :title_cont ,placeholder: "ALBUM NAME",class:" form-control "%>
  <%= form.submit class:"btn btn-danger"%>
  </div>
<%end%>

   <% @albums.each do |album| %>
      <div class="col-xxl-4 col-lg-4 col-md-6 col-sm-12 g-4">
        <div class=" card h-100 w-100 ">
           <% if album.cover_image.attached?%>
             <%= image_tag url_for(album.cover_image),class: "mx-auto h-75 w-100"%>
          <%end%>          
          <div class="card-body mx-auto">
            <h5 class="btn btn-danger"><%= link_to album.title, album ,class:"text-light text-decoration-none " %></h5>
            <h5 class="btn  btn-danger"><%= link_to "Destroy", album_path(album), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } , class: "text-light text-decoration-none img"%></h5>
          </div>
        </div>
      </div>
  <% end %>
  </div>

<div class = "col-md-8 offset-2 ">
  <% @albums.each do |album| %>
    <small class="btn btn-light btn-outline-danger  m-5">Tags: <%= raw album.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small>
  <% end %>
</div>
  

app/views/albums/my_albums.html.erb
<h1 class="text-center p-3 text-danger">Albums</h1>
<div class="row container-fluid">
  <% @albums.each do |album| %>
     <div class="col-xxl-4 col-lg-4 col-md-6 col-sm-12 g-4">
        <div class=" card h-100 w-100">
           <% if album.cover_image.attached?%>
             <%= image_tag url_for(album.cover_image),class: "mx-auto h-75 w-100"%>
          <%end%>          
          <div class="card-body mx-auto">
            <h5 class="btn btn-danger"><%= link_to album.title, album ,class:"text-light text-decoration-none " %></h5>
            <h5 class="btn  btn-danger"><%= link_to "Destroy", album_path(album), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } , class: "text-light text-decoration-none "%></h5>
          </div>
        </div>
     </div>
    <% end %>
</div>

app/views/albums/new.html.erb
<div class="container-fluid h-100 bgimg ">
<h1 class="text-danger text-center  ">New album</h1><br>
<%= render "form", album: @album %>
</div>

app/views/albums/show.html.erb
<h1 class="text-center text-danger"><%= @album.title %></h1>
<p class="text-center text-dark"><%= @album.body %></p>
<div class="row container-fluid">
   <% @album.images.each do|image| %>
      <div class="col-xxl-4 col-lg-4 col-md-6 col-sm-12 g-4">
        <div class=" card h-100 w-100 ">
          <img src="<%=url_for(image) %> " type="<%= image.content_type %>" class="h-75 w-100">
          <div class="card-body mx-auto">
             <h5 class="btn  btn-danger"><%= link_to "DESTROY" ,remove_image_album_path(@album,image_id: image.id), data:{
             turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-light text-decoration-none "%></h5>
            </div>
        </div>
      </div>
    <% end %>
  </div>
<div class= "text-center">
 <h5 class="btn btn-danger btn-lg mt-5  "><%= link_to "ADD MORE IMAGES",edit_album_path(@album),class:"text-light text-decoration-none " %></h5>
</div>
  

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light ">
          <div class="container-fluid">
            <a class="navbar-brand text-danger fs-4" href="<%= root_path(@album) %> "><%= image_tag "photos/logo1.png",style:"height:35px;width:50px;"%>PHOTO GALLERY </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
              <ul class="navbar-nav mb-2 mb-lg-0 ">
                <li class="nav-item">
                  <a class="nav-link active text-dark me-4 fs-5" aria-current="page" href="<%= root_path(@album) %>">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link  text-dark me-4 fs-5" href="<%= new_album_path  %>">New Album</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link  text-dark me-4 fs-5" href="<%= my_albums_path	%>">My Album</a>
                </li>
                <li class="nav-item">
                <% if user_signed_in? %>
                  <li> <%= link_to "Edit", edit_user_registration_path ,class:"nav-link  text-dark text-decoration-none me-4 fs-5"%></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, data: {
                  turbo_method: :delete},class:"nav-link  text-dark text-decoration-none fs-5"%></li>
                <%else%>
                 <li> <%= link_to "Sign Up", new_user_registration_path, class:"nav-link  text-dark text-decoration-none me-4 fs-5"%></li>
                 <li><%= link_to "Sign In", new_user_session_path, class:"nav-link  text-dark text-decoration-none fs-5" %></li>
                <% end%>                           
              </ul>
              <%# <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search Album" aria-label="Search">
                <button class="btn btn-outline-danger" type="submit">Search</button>
              </form> %>
            </div>
          </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!--for tags property-->
    <%= javascript_importmap_tags %>
    <!--css working for all media-->
    <%= stylesheet_link_tag "application", media:"all"%>
  </head>

  <body>
   
       <%= render "/layouts/navbar"%>
           
         <%= yield %>
         <p class="notice text-center fs-4 text-danger"><%= notice %></p>
          <p class="alert text-center fs-4 text-danger"><%= alert %></p>
         <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <script>
  $(document).on('ready page:load', function () {
    $('#post_tag_ids').chosen({
      allow_single_deselect: true,
      width: '100%'
    })
  });
</script>
</body>
</html>